language: java
sudo: required
services:
  - docker
stages:
  - build
  - push_docker_image 
jobs: 
  include:
    - stage: build 
      script:  
        - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        - mv lein ~/bin
        - chmod a+x ~/bin/lein
        - lein 
        - make libs 
        - make test
        - make clean all
        - mv dockerfiles/* build 
        - cd build && ls
        - docker build -f newsfeedDockerfile -t anyu686/ci-test:newsfeed .
        - docker build -f quoteDockerfile -t anyu686/ci-test:quote .
        - docker build -f frontendDockerfile -t anyu686/ci-test:frontend .
#    - stage: push_docker_image
#       script:
#        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#        - docker push anyu686/ci-test:newsfeed
#        - docker push anyu686/ci-test:quote
#        - docker push anyu686/ci-test:frontend
