language: java
sudo: required
services:
  - docker
stages: build
jobs: 
  include:
    - stage: build 
      script:  
        - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        - mv lein ~/bin
        - chmod a+x ~/bin/lein
        - lein 
        - make libs 
        - make test
        - make clean all
        - mv dockerfiles/* build 
        - cd build && ls
        - docker build -f newsfeedDockerfile -t newsfeed .
        - docker build -f quoteDockerfile -t quote .
        - docker build -f frontendDockerfile -t frontend .
