language: java
sudo: required
services:
  - docker
install:
 - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
 - mv lein ~/bin
 - chmod a+x ~/bin/lein
 - lein 
script:
 - make libs 
 - make test
 - make clean all
 - docker build -f newsfeedDockerfile
 - docker build -f quoteDockerfile 
 - docker build -f frontendDockerfile 
