language: java
sudo: required
services:
  - docker
stages:
  - build
  - push_docker_image 
jobs: 
  include:
    - stage: build 
      script:  
        - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        - mv lein ~/bin
        - chmod a+x ~/bin/lein
        - lein 
        - make libs 
        - make test
        - make clean all
        - mv dockerfiles/* build 
        - cd build && ls
        - docker build -f newsfeedDockerfile -t anyu686/newsfeed .
        - docker build -f quoteDockerfile -t anyu686/quote .
        - docker build -f frontendDockerfile -t anyu686/frontend .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push anyu686/newsfeed
        - docker push anyu686/quote
        - docker push anyu686/frontend
